### ISSUE TITLE
Add multiple containers capability on yaml

### ISSUE THREAD

**Issue by jairovadillo** [21ButtonsX/ecs-deployer#3]
Right now each service/task definition can have only one container. There are some cases when it's useful to have a multi-container declaration:

```
web:
  main:
    command: python ...
    memory: 512
    cpu: 256
  helper:
    command: python ...
    memory: 512
    cpu: 256
```
