### ISSUE TITLE
different container size per environment

### ISSUE THREAD

**Issue by edu21b** [21ButtonsX/ecs-deployer#8]
dear developers, I think you have developed an amazing project. however, the procfile can only contain one container size, which should be production.

```
 release:
  command: python backshop/manage.py migrate --noinput
  memory: 512
  cpu: 256
```

maybe we should have different sizes or environments?
